### PR TITLE
update rust tool chain

### PR DESCRIPTION
**Pull request by yaoxin1995**

### CODE REVIEW

**Review by QuarkContainer — APPROVED** [review]

**Comment by shrik3** [comment]
why does this PR contain a merge commit ca64eb29c81cb01c240b87e09c2111eca9a7bacb ?

**Comment by shrik3** [comment]
@QuarkContainer looks like the other way around?

"Merge branch 'main' into new_tool_chain"

**Comment by yaoxin1995** [comment]
@shrik3 , Yulin adds this merge commit to resolve a one-line conflict

**Comment by shrik3** [comment]
> @shrik3 , Yulin adds this merge commit to resolve a one-line conflict

Then please rebase against main before merging into main.  The commit log is confusing.

**Comment by QuarkContainer** [comment]
@shrik3 make sensor. Will make sure this later. :-)

**Pull request merged**
