### PR TITLE
[RFC] add rustfmt config

### PR DESCRIPTION
**Pull request by shrik3**
**why**  
It's helpful to have a automated code formatter. Rust's stock [rustfmt](https://github.com/rust-lang/rustfmt) works pretty nicely by default. And you are likely already using it if you editor has a rust plugin (such as vs code's rust-analyzer)

However the default config could be subject to upstream updates, and may be inconsistent across different developers‘ environments. I'd like to propose that we add a config to the repo to make code formatting consistent. I dump a default config.

**how**
Most [editors support it via plugins](https://github.com/rust-lang/rustfmt?tab=readme-ov-file#running-rustfmt-from-your-editor) with a few (if any) settings.

You could also use it to manually, either via cargo, calling rustfmt directly, or piping to stdin. The [rustfmt wiki](https://github.com/rust-lang/rustfmt?tab=readme-ov-file#running) has detailed instructions so I won't repeat here.

**rfc**  
You may want to take a look at the `.rustfmt.toml` and try the rustfmt tool out. If you have coding style preference other than the default , feel free to suggest changes :-)

**note** 
I'm not proposing a global formatting of the whole codebase, because it may break the vcs... The automated formatting should only apply to new code.

```
$ rustfmt --version
rustfmt 1.7.0-nightly (88189a7 2024-01-19)
$ rustfmt --print-config default > .rustfmt.toml
```

### CODE REVIEW

**Review by QuarkContainer — APPROVED** [review]

**Comment by QuarkContainer** [comment]
@shrik3 Your change is much better than mine for the comments. Please keep yours and I have closed mine.

**Comment by shrik3** [comment]
@QuarkContainer let's keep this open for several days and see if others have a say.

**Comment by yaoxin1995** [comment]
@shrik3  So Quark now supports rustup toolchain version `1.7.0-nightly (88189a7 2024-01-19)`?

**Comment by shrik3** [comment]
> @shrik3 So Quark now supports rustup toolchain version `1.7.0-nightly (88189a7 2024-01-19)`?

No, that is the version of rustfmt, so is the option `required-version`. I don't think it has anything to do with the rustc toolchain version.

The rust edition is set to "2015". Do you have a older rustfmt install? What's the output of your `rustfmt --version` ?

**Comment by yaoxin1995** [comment]
No, I'm just curious if you've updated Quark's toolchain. It is outdated, so some rust programs may no longer compile with it.

**Pull request merged**
