### PR TITLE
Backtrack

### PR DESCRIPTION
**Pull request by QuarkContainer**
I don't know how to install llvm-addr2line so I use addr2line instead.

### CODE REVIEW

**Comment by shrik3** [comment]
> I don't know how to install llvm-addr2line so I use addr2line instead.

with ubuntu I think you can simply install the llvm package. The llvm-addr2line tool would be included.

I tested both, the llvm-addr2line is much faster (almost immediate feedback) than the old addr2line tool.

**Review by shrik3 — APPROVED** [review]
please use the "squash and merge" option, as this PR contains already-merged commits.

**Comment by QuarkContainer** [comment]
@shrik3 for the "install the llvm package.", could you please let me know how to install that? I try to run "llvm", seems the system doesn't know that either.

**Comment by shrik3** [comment]
> @shrik3 for the "install the llvm package.", could you please let me know how to install that? I try to run "llvm", seems the system doesn't know that either.

I assume you are using ubuntu?

does `sudo apt install llvm` work for you? Perhaps you need to do `sudo apt update`first

**Pull request merged**
