### PR TITLE
aarch64: context_swap - adjust 3rd & 4rth parameter

### PR DESCRIPTION
**Pull request by chl337**
#1337 
P.S. @mhomidi

### CODE REVIEW

**Comment by shrik3** [comment]
btw I don't see why the context_swap abi has to provide 1 and 0 through parameters. Can't we just use asm literals?

**Comment by chl337** [comment]
> btw I don't see why the context_swap abi has to provide 1 and 0 through parameters. Can't we just use asm literals?

I don't know if @QuarkContainer has a plan for 
 ``` rust
    pub fn context_swap(_fromCxt: u64, _toCtx: u64, _one: u64, _zero: u64);
```
Otherwise, I could drop the two last arguments.

**Comment by QuarkContainer** [comment]
@chl337 I have no plan for that. Please go ahead to drop those.

**Review by mhomidi — APPROVED** [review]

**Comment by QuarkContainer** [comment]
@chl337 is that ok to merge this before your new fix?

**Comment by chl337** [comment]
I guess so... Unfortunately, I will not be active till 16/17.08

Cheers

**Pull request merged**
