### PR TITLE
Context swap cleanup

### PR DESCRIPTION
**Pull request by chl337**

### CODE REVIEW

**Review by shrik3 — APPROVED** [review]

**Comment by shrik3** [comment]
is this tested on both archs? If so please go ahead and merge it.

**Comment by chl337** [comment]
> is this tested on both archs? If so please go ahead and merge it.

@QuarkContainer I think I have already tested in x86, but could you try it also?

**Comment by QuarkContainer** [comment]
@chl337 will do

**Comment by QuarkContainer** [comment]
@chl337 it works in x86.

**Pull request merged**
