### PR TITLE
chore: URING: remove deadcode

### PR DESCRIPTION
**Pull request by chl337**

### CODE REVIEW

**Comment by chl337** [comment]
@shrik3 ping:)

**Review by QuarkContainer — COMMENTED** [review]
The code is related to the IORING_REGISTER_FILES_UPDATE feature. In some old Linux version (might be 5.8), we have to add register the fd before use them with IO_Uring. But if we enable support this, we have to create a large array which might cover all the fd range for example 0~1024 or 0~4096 etc. As some application might use very large amount fds, it will take much memory. 

I tried to add the configuraiton UringFixedFile to enable/disable this feature for Linux version compatibility. But I forget to update the code. 

Ideally, we'd better enable/disable this based on Linux version and expend and shrink the fd array.

I think we'd better to keep the code and add a issure or work item to enable the feature when we have bandwidth.

**Comment by shrik3** [comment]
> I think we'd better to keep the code and add a issure or work item to enable the feature when we have bandwidth.

@chl337  In which case, please mark the functions in question with `todo!()`, comment out the references (with some notes perhaps) and write a memo somewhere (or maybe open an issue).

**Comment by chl337** [comment]
> comment out the references (with some notes perhaps) 

That's a ghost state that I am not really fond with.

**Comment by QuarkContainer** [comment]
@chl337 I agree with you. Please remove this now. Could you please also file an issue with the commit id so that we can reference the code when need it.

**Review by QuarkContainer — APPROVED** [review]

**Pull request merged**
