### PR TITLE
[RFC]Armdev correct missing PTDescriptor Flags for mappings

### PR DESCRIPTION
**Pull request by chl337**
WIP related to #1097.
NOTE: Relevant commit: 4b35919f0e8ea5bbef42f7cf31e5fbe549d7df3c
NOTE: When concluded will be rebased against [armdev-banch](https://github.com/QuarkContainer/Quark/tree/armdev)
NOTE: Current state is _experimental_, can (**and will**) lead to unknown errors if the same type of fault reappears.

### CODE REVIEW

**Comment by abel-von** [comment]
I got a signal 11,  for example when executing `docker run -ti --runtime=quark_d ubuntu sh`, the log is like below.
It's strange that I got a page fault with address very small, like 0x70. 

```
[INFO] [1/43c0180000|0] DFSC/IFSC == 0x5, FAR == 0x70, acces-type fault == r--, during address translation == false.
[INFO] [1/630794] hypecall: 8, paras: 43c019c7a8 0 0 0
[INFO] [1/43c0180000|0] VM: PageFaultHandler - FAR: 0x70, PC: 0x2b76ec4e2cd8,TTBR: 0x43c0401000, is-user: true, error code: 0x24.
[INFO] [1/631205] hypecall: 8, paras: 43c019c7a8 0 0 0
[ERROR] [1/43c0180000|0] VM: The map is 3ffffff000-8000000000 rw-p 00000000 00:00 0
a000000000-a000001000 r--p 400052b000 00:00 0                            [vvar]
a000001000-a000003000 r-xs 400052c000 00:00 0                            [vdso]
e1ac93ed000-e1ac940a000 r-xp 00000000 00:44bca 281546
e1ac940a000-e1ac940b000 rwxp 0001d000 00:44bca 281546
e1ac941b000-e1ac941d000 rw-p 0001e000 00:44bca 281546
e1ac941d000-e1ac941e000 rwxp 00020000 00:44bca 281546
e1ac941e000-e1ac9420000 rw-p 00000000 00:00 0                            [elf:static]
2b76ec400000-2b76ec425000 r-xp 00000000 00:44db5 282037
2b76ec425000-2b76ec426000 rwxp 00025000 00:44db5 282037
2b76ec426000-2b76ec428000 rw-p 00000000 00:00 0
2b76ec428000-2b76ec42c000 r--p 00000000 00:46c5d 289885
2b76ec43e000-2b76ec441000 rw-p 0002e000 00:44db5 282037
2b76ec441000-2b76ec442000 rwxp 00031000 00:44db5 282037
2b76ec450000-2b76ec5d7000 r-xp 00000000 00:44dc7 282055
2b76ec5d7000-2b76ec5ec000 ---p 00187000 00:44dc7 282055
2b76ec5ec000-2b76ec5f0000 r--p 0018c000 00:44dc7 282055
2b76ec5f0000-2b76ec5f2000 rw-p 00190000 00:44dc7 282055
2b76ec5f2000-2b76ec5ff000 rw-p 00000000 00:00 0
7fd3d2120000-7fd3d2920000 rw-p 00000000 00:00 0                          [stack]
, fault address is not part of it.

```

**Comment by abel-von** [comment]
I got a signal 11,  for example when executing `docker run -ti --runtime=quark_d ubuntu sh`, the log is like below.
It's strange that I got a page fault with address very small, like 0x70. 

```
[INFO] [1/43c0180000|0] DFSC/IFSC == 0x5, FAR == 0x70, acces-type fault == r--, during address translation == false.
[INFO] [1/630794] hypecall: 8, paras: 43c019c7a8 0 0 0
[INFO] [1/43c0180000|0] VM: PageFaultHandler - FAR: 0x70, PC: 0x2b76ec4e2cd8,TTBR: 0x43c0401000, is-user: true, error code: 0x24.
[INFO] [1/631205] hypecall: 8, paras: 43c019c7a8 0 0 0
[ERROR] [1/43c0180000|0] VM: The map is 3ffffff000-8000000000 rw-p 00000000 00:00 0
a000000000-a000001000 r--p 400052b000 00:00 0                            [vvar]
a000001000-a000003000 r-xs 400052c000 00:00 0                            [vdso]
e1ac93ed000-e1ac940a000 r-xp 00000000 00:44bca 281546
e1ac940a000-e1ac940b000 rwxp 0001d000 00:44bca 281546
e1ac941b000-e1ac941d000 rw-p 0001e000 00:44bca 281546
e1ac941d000-e1ac941e000 rwxp 00020000 00:44bca 281546
e1ac941e000-e1ac9420000 rw-p 00000000 00:00 0                            [elf:static]
2b76ec400000-2b76ec425000 r-xp 00000000 00:44db5 282037
2b76ec425000-2b76ec426000 rwxp 00025000 00:44db5 282037
2b76ec426000-2b76ec428000 rw-p 00000000 00:00 0
2b76ec428000-2b76ec42c000 r--p 00000000 00:46c5d 289885
2b76ec43e000-2b76ec441000 rw-p 0002e000 00:44db5 282037
2b76ec441000-2b76ec442000 rwxp 00031000 00:44db5 282037
2b76ec450000-2b76ec5d7000 r-xp 00000000 00:44dc7 282055
2b76ec5d7000-2b76ec5ec000 ---p 00187000 00:44dc7 282055
2b76ec5ec000-2b76ec5f0000 r--p 0018c000 00:44dc7 282055
2b76ec5f0000-2b76ec5f2000 rw-p 00190000 00:44dc7 282055
2b76ec5f2000-2b76ec5ff000 rw-p 00000000 00:00 0
7fd3d2120000-7fd3d2920000 rw-p 00000000 00:00 0                          [stack]
, fault address is not part of it.

```

**Comment by chl337** [comment]
If I understand correctly, the alignment check is per default _disabled_ in the VMM => **SCTLR.A==0**. When the fault happens, the **PC=0xF86A6803** translates to **LDR X3, [X0, X10]**, which should allow unaligned access in Normal-Memory.

**Comment by chl337** [comment]
With regard to [above](https://github.com/QuarkContainer/Quark/pull/1102#issuecomment-1952256265), I see that the AttrIndex-field in the PTE for the FAR points to the wrong MemoryAttributes. So, instead of emulating the access in EL1 we should actually _"fix"_ the PTE-flags.

**Comment by CharlyYu** [comment]
Do we set some page not Normal memory?

**Comment by chl337** [comment]
> Do we set some page not Normal memory?

In fact, I think it gets overwritten. I will add a _"provisory"_ fix that resets the type depending on the mapping region. IIRC only the Hypercall-MMIO area is tagged as DeviceMemory.

**Comment by shrik3** [comment]
> IIRC only the Hypercall-MMIO area is tagged as DeviceMemory.

Actually it is non-cacheable normal memory. It triggers MMIO because there is no physical memory backing it.

**Comment by chl337** [comment]
> > IIRC only the Hypercall-MMIO area is tagged as DeviceMemory.
> 
> Actually it is non-cacheable normal memory. It triggers MMIO because there is no physical memory backing it.

Thanks for the reminder, totally missed it.

**Comment by chl337** [comment]
As there is no really need for an EL1 AlignmentFault-Handler here, I will open another WIP that handles possible cases.

**Review by CharlyYu — APPROVED** [review]

**Pull request merged**
